### ISSUE TITLE
Report comments

### ISSUE THREAD

**Issue by amartinhuertas** [GiteonCaulfied/COMP4560_stokes_ml_project#14]
Let us use this issue to gather comments on the report

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas,

> @GiteonCaulfied ... are you explicitly referencing Figures from the text of the report using the `\ref{label}` command from the text?

I am not explicitly referencing figures. Instead, I just write things like "As shown by the following figures..." or "The following figures show that...". Is referencing explicitly better? If it is, I will be using `\ref{label}` command instead.

**Comment by amartinhuertas** [comment]
> Is referencing explicitly better? If it is, I will be using \ref{label} command instead.

Yes, it is better (and a requirement for scientific publications in general).  Note that you need to use, e.g., \label{figure:mantle_convection} within the caption of the figure, and then use \ref{figure:mantle_convection} in the text.
Put the source of the figure right below the paragraph that first references it.

Using figure identifiers in the text is not ambiguous anymore. Besides, you will have the figures placed closer to the text that first references them. Right now, the algorithm within the latex compiler that displays figures, has a lot of freedom to float them up around the report.

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas,

The figures are now explicitly referenced. Also, a list of "thank you" has been added in the Acknowledgement chapter now.

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas @rhyshawkins,

An updated report has been pushed to the repo, based on @rhyshawkins's comment I received this afternoon.

for one of the questions in @rhyshawkins's comment,

> For LSTM, do we really randomly shuffle. I thought we treat batches of adjacent timesteps?

The answer is I randomly shuffle simulation files instead of adjacent timesteps since I set the input-output length to 50:50 (use 50 to predict the rest 50) and one simulation only has 100 time steps in total. I just realized that I can set a shorter input-output length like 20:20 so that we can shuffle adjacent timesteps (every sequences of 40 time steps cropped from every simulations, in this case we have 59 more data to train with in one simulation) instead of files. However, there's no time to do that now so I can only add it to the future work. Sorry about that.

**Comment by amartinhuertas** [comment]
> An updated report has been pushed to the repo, based on @rhyshawkins's comment I received this afternoon.

Ok. I will go over the report tomorrow and also send you an annotated PDF, hopefully at the end of the day.

**Comment by amartinhuertas** [comment]
We are still missing the x-axis and y-axis labels in Figs 3.3 and 3.4.  @sghelichkhani @rhyshawkins please help.

**Comment by rhyshawkins** [comment]
The x-axis for 3.3 is basically the index into the input vector. The x-label could simply be "Input Vector (index)"

Similarly for 3.4, the x-axis for 3.4 is index into the flattened output vector, which are the spherical harmonics coefficients that could be individually labelled but would be too dense to read, instead I would suggest labelling this "Spherical Harmonic Coefficients". For this reason, it is better to plot the output on the globe as is done in subsequent figures.

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas @rhyshawkins,

The x-axis and y-axis of these two figures are added now.

**Comment by amartinhuertas** [comment]
> Ok. I will go over the report tomorrow and also send you an annotated PDF, hopefully at the end of the day.

@GiteonCaulfied, FYI, I am going over the report and applying changes directly to the source files (mostly cosmetic). Once I finish, I will hand-write annotate the resulting PDF with my comments. (I will let you know the commit corresponding to the PDF I have annotated).

In the meantime, I see that all the loss evolution versus epoch plots have linear scale in the y-axis. As a result, it might seem that the loss rapidly achieves a plateau, when it does not actually. Can you please take one of these plots, and check whether visualization improves when using log scale for the y-axis?

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas,

I've been reading the changes you made since this morning, thanks for the effort!

As for the loss evolution versus epoch plots, I've tried to use log scale for the y-axis and the visualization looks better now (not looking like it achieves a plateau rapidly anymore), here's what the loss evolution for the FNN trained on interpolated dataset looks like after using log scale for the y-axis for your reference:

![download](https://github.com/GiteonCaulfied/COMP4560_stokes_ml_project/assets/79442884/75a777ee-7234-49a8-9086-aacc90d53e1a)


I'll generate new plots for all loss evolutions so that I can replace the old ones as soon as possible once you finish.

**Comment by amartinhuertas** [comment]
> here's what the loss evolution for the FNN trained on interpolated dataset looks like after using log scale for the y-axis for your reference:

ok, that is another story

> I'll generate new plots for all loss evolutions so that I can replace the old ones as soon as possible once you finish.

ok, please work on this while I continue with the report.

**Comment by amartinhuertas** [comment]
I have already finished my passed over the document, and made mostly cosmetic changes to the sources. Now I am going to start annotating the PDF with misc comments. The version of the PDF I am annotating is the one corresponding to commit d587724d2bc895a6e25a4b3562f76a9e9e8e44f7

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas,

The report now has updated loss evolution figures using log scale for the y-axis.

Also, README is slightly modified by adding a link to the Interpolated Dataset on my OneDrive.

**Comment by GiteonCaulfied** [comment]
Hi @amartinhuertas @rhyshawkins @sghelichkhani ,

For the records, the latest version of the report is now submitted to Wattle.

As for the artefact part, Michael mentioned on Wattle announcement that:

> You are separately responsible for submitting your artefact to your supervisors in a way and format agreed with them.

Since this repository itself serves as my artefact, you can always check the files in this repository to mark them.

And finally, thank you all for being my supervisors over this semester, have a nice day :)
